name: Discord Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Используем встроенное действие

      - name: Set up Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        run: npm install

      - name: Check dependencies
        run: npm list

      - name: Stop previous bot instance
        run: |
          if [ -f "bot.pid" ]; then
            echo "Stopping previous instance with PID $(cat bot.pid)..."
            kill $(cat bot.pid) || echo "No process to kill"
            rm bot.pid
          fi

      - name: Run Discord bot
        env:
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          nohup node app.js & echo $! > bot.pid  # Запускаем бот в фоновом режиме и сохраняем PID

      - name: Trigger bot workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/timaroblox5/PineBot/actions/workflows/bot.yml/dispatches \
          -d '{"ref": "main"}'
          # Замените timaroblox5 и PineBot на соответствующие значения

  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Stop previous bot instance
        run: |
          if [ -f "bot.pid" ]; then
            echo "Stopping previous instance with PID $(cat bot.pid)..."
            kill $(cat bot.pid) || echo "No process to kill"
            rm bot.pid
          fi
