name: Pinebot Deployment

on:
  push:
    branches:
      - main  # Событие будет запускаться при каждом коммите в ветку main
  schedule:
    - cron: '*/1 * * * *'  # Каждую минуту

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Устанавливаем Node.js
        with:
          node-version: '20'  # Задаем версию Node.js

      - name: Start Discord bot
        env:
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}  # Настраиваем переменные окружения
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: node start.bat  # Запускаем бота
