name: Discord Bot

on:
  schedule:
    - cron: '*/1 * * * *'  # Каждую минуту

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: git clone https://github.com/timaroblox5/TimaSync-bot.git .

      - name: Set up Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        run: npm install

      - name: Check bot status and run if necessary
        env:
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Убедитесь, что токен добавлен в секреты
        run: |
          if ps -p $(pgrep -f "node app.js") > /dev/null; then
            echo "Bot is already running."
          else
            echo "Starting the bot..."
            nohup node app.js & echo $! > bot.pid  # Запускаем бот и сохраняем PID
          fi

      - name: Final check of bot status
        run: |
          if ps -p $(cat bot.pid) > /dev/null; then
            echo "Bot is running"
          else
            echo "Bot has stopped, please check the logs"
            exit 1  # Если бот не работает, завершаем с ошибкой
          fi