name: Discord Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        run: npm install

      - name: Stop previous bot instance
        run: |
          if [ -f "bot.pid" ]; then
            echo "Stopping previous instance..."
            kill $(cat bot.pid) || echo "No process to kill"
            rm bot.pid
          fi

      - name: Run Discord bot
        env:
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          nohup node app.js & echo $! > bot.pid

      - name: Wait for changes and restart if needed
        run: |
          while true; do 
            sleep 300  # Проверяем каждые 5 минут
            
            if git fetch && ! git diff --quiet origin/main; then
              echo "Changes detected, restarting bot..."
              if [ -f "bot.pid" ]; then
                kill $(cat bot.pid) || echo "No process to kill"
                rm bot.pid
              fi
              nohup node app.js & echo $! > bot.pid
            fi
          done