name: Deploy Discord Bot

on:
  schedule:
    - cron: '10 * * * *'  # Запуск каждые 59 минут (для второго job)

jobs:
  run_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 11  # Общее время выполнения job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Start Bot
      run: |
        echo "Starting bot..."
        node app.js &  # Запуск бота в фоновом режиме
        echo "Bot started with process ID $!"
        sleep 600  # Подождать 1 минут (60 секунд)
        echo "Stopping bot..."
        kill $!  # Остановить бот
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        MONGODB_CONNECT: ${{ secrets.MONGODB_CONNECT }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

  check_for_new_jobs:
    runs-on: ubuntu-latest
    if: github.event.schedule
    
    steps:
    - name: Execute additional tasks
      run: |
        echo "Executing additional tasks every 10 minutes..."