name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Переключено на v4
      with:
        node-version: '20'  # Указываем используемую версию Node.js

    - name: Install dependencies
      run: npm install

    - name: Install pm2 globally
      run: npm install -g pm2

    - name: Start Bot with pm2
      run: |
        pm2 start app.js --name discord-bot --watch --restart-delay 1000
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        MONGODB_CONNECT: ${{ secrets.MONGODB_CONNECT }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
