name: Pinebot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Install dependencies
        run: npm install

      - name: Check installed packages
        run: npm list

      - name: Stop old bot process
        run: |
          pm2 stop pinebot || echo "No previous instance found."

      - name: Cleanup old processes
        run: |
          pm2 delete pinebot || echo "No previous instance found."

      - name: Start Discord bot
        env:
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          pm2 start app.js --name "pinebot" --watch --ignore-watch="node_modules" --max-restarts 30 --update-env
          pm2 save  # Сохраняем текущее состояние PM2
          echo "Bot is running."
