name: Pinebot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check installed packages
        run: npm list

      - name: Start Discord bot
        env:
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          nohup node app.js > output.log 2>&1 &
          echo "Bot is running."
