name: Discord Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g pm2  # Устанавливаем pm2 глобально

      - name: Install dependencies
        run: npm install

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet HEAD^ HEAD || echo "changed=true" >> $GITHUB_ENV

      - name: Start or restart Discord bot
        if: env.changed == 'true'
        env:
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          # Запускаем или перезапускаем бота с помощью pm2
          pm2 start app.js --name "discord-bot" --watch --ignore-watch="node_modules" || pm2 restart "discord-bot"
          pm2 save  # Сохраняем текущее состояние pm2
          echo "Bot is running or restarted."

      - name: Cleanup old processes
        if: env.changed == 'true'
        run: |
          pm2 delete "discord-bot" || echo "No previous instance found."
