name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check if app.js exists
        run: |
          if [ -f app.js ]; then
            echo "file exists"
          else
            echo "file does not exist"
            exit 1
          fi

      - name: Run app.js
        run: node app.js
