name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Укажи нужную версию Node.js

      - name: Run app.js
        env:
          DISCORD_TOKEN: '${{ secrets.DISCORD_TOKEN }}'
          CLIENT_SECRET: '${{ secrets.CLIENT_SECRET }}'
          MONGODB_PASSWORD: '${{ secrets.MONGODB_PASSWORD }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PINEBOT_TOKEN: '${{ secrets.PINEBOT_TOKEN }}'
           # Здесь добавляем переменные окружения
        run: node app.js
